apiVersion: batch/v1
kind: Job
metadata:
  name: "pvc-mount"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: "pvc-mount"
        image: busybox:1.28
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        volumeMounts:
          - mountPath: "/pvc-data"
            name: task-pv-storage
      securityContext:
        runAsUser: 1001
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: redis-data-cadc-openharbor-redis-master-0
